app/__init__.py
from .app import create_app

app/app.py
from flask import Flask
from .views import home,add_word,delete_word,search,show_list,update_word

def create_app():

    app = Flask(__name__, template_folder="templates", static_folder="static")
    app.config.from_pyfile("config.py")

    if app.config["VERSION"] =="1.0.1":
        pass
    elif app.config["VERSION"] == "1.0.2":
        pass

    app.register_blueprint(home.bp)
    app.register_blueprint(add_word.bp)
    app.register_blueprint(delete_word.bp)
    app.register_blueprint(search.bp)
    app.register_blueprint(show_list.bp)
    app.register_blueprint(update_word.bp)



    return app

app/views/add_word.py
from flask import render_template, request, Blueprint, redirect, url_for
from app.main1 import *

bp = Blueprint("add_word", __name__, template_folder="../templates")


@bp.route("/addword", methods=["GET", "POST"])
def AddWord():
    print("gelen istek tipi****", request.method)

    if request.method == "POST":

        word = request.form.get("word")
        meaning = request.form.get("meaning")
        sample = request.form.get("sample")
        if word and meaning and sample:
            word_list = Dictionary("app/deneme.json")
            word_list.insert_word(word=word, meaning=meaning, sample=sample)

            return redirect(url_for("show_list.ShowList"))

    return render_template('add_word.html')

app/views/delete_word.py
from flask import render_template, request, Blueprint, redirect, url_for
from app.main1 import *

bp = Blueprint("delete_word", __name__, template_folder="../templates")


@bp.route("/deleteword", methods=["GET", "POST"])
def DeleteWord():

    if request.method == 'POST':
        value = request.form.get("value")
        if value:
            word_list = Dictionary("app/deneme.json")
            word_list.delete_word(value=value)
            return redirect(url_for("show_list.ShowList"))
    return render_template('delete.html')

app/views/home.py
from flask import render_template, request, Blueprint,redirect,url_for

bp = Blueprint("home",__name__,template_folder="../templates")

@bp.route("/")

def Index():
    return render_template("index.html")

app/views/search.py
from flask import render_template, request, Blueprint
from app.main1 import *

bp = Blueprint("search", __name__, template_folder="../templates")


@bp.route("/searchlist", methods=["GET", "POST"])
def SearchList():
    if request.method == 'POST':
        value = request.form.get("value")

        if value:
            meaning_list = Dictionary("app/deneme.json").search_word(value=value)
            data = meaning_list
            print(meaning_list)
            data_value= value
            return render_template('search_result.html', context=data,word_value=data_value)

    return render_template('search.html')

app/views/show_list.py
from flask import render_template, request, Blueprint
from app.main1 import *

bp = Blueprint("show_list", __name__, template_folder="../templates")


@bp.route("/showlist", methods=["GET"])
def ShowList():
    word_list = Dictionary("app/deneme.json").word_list
    data=word_list

    return render_template('list_words.html', context=data)

app/views/update_word.py
from flask import render_template, request, Blueprint, redirect, url_for
from app.main1 import *

bp = Blueprint("update_word", __name__, template_folder="../templates")


@bp.route("/updateword", methods=["GET", "POST"])
def UpdateWord():

    if request.method == 'POST':
        new_value = request.form.get("new_value")

        if new_value:
            word_list = Dictionary("app/deneme.json")
            word = request.form.get("word")
            meaning = request.form.get("meaning")
            new_value = request.form.get("new_value")
            word_list.edit_word(word=word, meaning=meaning, new_value=new_value)

            return redirect(url_for("show_list.ShowList"))

    return render_template('update.html')

app/templates/add_word.html
{% block body_content %}
<html>

<head>

    <meta charset="utf-8">
    <meta name="author" content="templatemo">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"
          rel="stylesheet">

    <title>Liberty Template - Create NFT Page</title>

        <!-- Bootstrap core CSS -->
    <link href="static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">



    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="static/assets/css/fontawesome.css">
    <link rel="stylesheet" href="static/assets/css/templatemo-liberty-market.css">
    <link rel="stylesheet" href="static/assets/css/owl.css">
    <link rel="stylesheet" href="static/assets/css/animate.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
    <!--

    TemplateMo 577 Liberty Market

    https://templatemo.com/tm-577-liberty-market

    -->
</head>
<body>
<div class="item-details-page">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="section-heading">
                    <div class="line-dec"></div>
                    <h2>Add For <em>Your Words</em> Here.</h2>
                    <h2><br></h2>
                    <h2><br> <br></h2>
                    <h2><br> <br></h2>
                    <h2><br> <br></h2>

                </div>
            </div>
                        <div class="col-lg-4">
                <div class="main-button">
                    <a href="{{url_for('home.Index')}}">Anasayfaya Dönmek İçin Tıklayın</a>
                </div>
            </div>
            <div class="col-lg-12">

                <form id="contact" action="{{url_for('add_word.AddWord')}}" method="POST" >

                    <div class="row">
                        <div class="col-lg-4">
                            <fieldset>
                                <label for="word">Word</label>
                                <input type="text" name="word" id="word" placeholder="Please enter your word"
                                       autocomplete="on" required>
                            </fieldset>
                        </div>
                        <div class="col-lg-4">
                            <fieldset>
                                <label for="meaning">Meaning</label>

                                <input type="text" name="meaning" id="meaning"
                                       placeholder="Please enter your meaning" autocomplete="on" required>
                            </fieldset>
                        </div>
                        <div class="col-lg-4 ">
                            <fieldset>
                                <label for="sample">Sample</label>

                                <input type="text" name="sample" id="sample"
                                       placeholder="Please enter your sample." autocomplete="on" required>
                            </fieldset>
                        </div>

                        <div class=" col-md-6 offset-md-3">
                            <fieldset>
                                <button type="submit" id="form-submit" class="orange-button">Submit</button>
                            </fieldset>
                        </div>
                    </div>
                </form>
            </div>


        </div>
    </div>
</div>
</body>
</html>
{% endblock %}

app/templates/delete.html
{% block body_content %}
<html>
<head>

    <meta charset="utf-8">
    <meta name="author" content="templatemo">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"
          rel="stylesheet">

    <title>Liberty Template - Create NFT Page</title>

    <!-- Bootstrap core CSS -->
    <link href="static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="static/assets/css/fontawesome.css">
    <link rel="stylesheet" href="static/assets/css/templatemo-liberty-market.css">
    <link rel="stylesheet" href="static/assets/css/owl.css">
    <link rel="stylesheet" href="static/assets/css/animate.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
    <!--

    TemplateMo 577 Liberty Market

    https://templatemo.com/tm-577-liberty-market

    -->
</head>
<body>
<div class="item-details-page">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="section-heading">
                    <div class="line-dec"></div>
                    <h2> WORDS <em> DELETE </em></h2>
                    <h2><br></h2>
                    <h2><br></h2>
                    <h6><br></h6>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="main-button">
                    <a href="{{url_for('home.Index')}}">Anasayfaya Dönmek İçin Tıklayın</a>
                </div>
            </div>
            <div class="col-md-6 offset-md-3">
                <form id="contact" action="" method="post">
                    <div class="row">
                        <div class="col-md-6 offset-md-3">
                            <form action="{{url_for('delete_word.DeleteWord')}}" method="POST">

                                <fieldset>
                                    <label for="value"><h3>Enter word</h3></label>

                                    <input type="title" name="value" id="value" placeholder="Please enter your word"
                                           autocomplete="on" required formmethod="post">
                                </fieldset>
                            </form>
                        </div>

                        <div class=" col-md-6 offset-md-3">
                            <fieldset>
                                <button type="submit" id="form-submit" class="orange-button" formmethod="post">Delete
                                </button>
                            </fieldset>
                        </div>
                    </div>
                </form>
            </div>


        </div>
    </div>
</div>
</body>
</html>
{% endblock %}

app/templates/index.html
{% block body_content %}
<html>

<head>

    <meta charset="utf-8">
    <meta name="author" content="templatemo">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"
          rel="stylesheet">

    <title>Liberty Template - Create NFT Page</title>

    <!-- Bootstrap core CSS -->
    <link href="static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="static/assets/css/fontawesome.css">
    <link rel="stylesheet" href="static/assets/css/templatemo-liberty-market.css">
    <link rel="stylesheet" href="static/assets/css/owl.css">
    <link rel="stylesheet" href="static/assets/css/animate.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
    <!--

    TemplateMo 577 Liberty Market

    https://templatemo.com/tm-577-liberty-market

    -->
</head>

<body>

<!-- ***** Preloader End ***** -->

<!-- ***** Header Area Start ***** -->
<header class="header-area header-sticky">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <nav class="main-nav">
                    <!-- ***** Logo Start ***** -->

                    <!-- ***** Logo End ***** -->
                    <!-- ***** Menu Start ***** -->
                    <ul class="nav">
                        <li><a href="{{url_for('add_word.AddWord')}}">Add Word</a></li>
                        <li><a href="{{url_for('show_list.ShowList')}}">Show List</a></li>
                        <li><a href="{{url_for('search.SearchList')}}">Search Word</a></li>
                        <li><a href="{{url_for('delete_word.DeleteWord')}}">Delete Word</a></li>
                        <li><a href="{{url_for('update_word.UpdateWord')}}">Update Word</a></li>
                    </ul>
                    <a class='menu-trigger'>
                        <span>Menu</span>
                    </a>
                    <!-- ***** Menu End ***** -->
                </nav>
            </div>
        </div>
    </div>
</header>
<div class="main-banner">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 align-self-center">
                <div class="header-text">
                    <h6></h6>
                    <h2>
                        <br>
                    </h2>

                    <h2>Sözlükte bulunan Kelimeleri listeleme,silme,güncelleme,arama işlemlerinden herhangi bir işlem
                        için seçim yapın</h2>
                    <h2>
                    </h2>
                    <br>
                    <br>
                    <br>
                    <br>


                </div>
            </div>
        </div>

    </div>
</div>


</body>
</html>
{% endblock %}

app/templates/list_words.html
{% block body_content %}
<html>
<head>

    <meta charset="utf-8">
    <meta name="author" content="templatemo">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"
          rel="stylesheet">

    <title>Liberty Template - Create NFT Page</title>

        <!-- Bootstrap core CSS -->
    <link href="static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">



    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="static/assets/css/fontawesome.css">
    <link rel="stylesheet" href="static/assets/css/templatemo-liberty-market.css">
    <link rel="stylesheet" href="static/assets/css/owl.css">
    <link rel="stylesheet" href="static/assets/css/animate.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
    <!--

    TemplateMo 577 Liberty Market

    https://templatemo.com/tm-577-liberty-market

    -->

</head>

<body>
<div class="create-nft">


    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="section-heading">
                    <div class="line-dec"></div>
                    <h2>Sözlükte Bulunan Kelimelerin Listesi</h2>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="main-button">
                    <a href="{{url_for('home.Index')}}">Anasayfaya Dönmek İçin Tıklayın</a>
                </div>
            </div>
            {% for word in context %}
            <div class="col-lg-4">
                <div class="item first-item">
                    <h4>Word: {{ word.word }}</h4>
                    <p>Meaning: {{ word.meaning }}</p>
                    <p>Sample: {{ word.sample }}</p>
                </div>
                <hr/>
            </div>
            {% endfor %}

            <h2><br> <br></h2>
            <h2><br> <br></h2>
            <h2><br> <br></h2>
            <h2><br> <br></h2>
        </div>
    </div>
</div>

</body>
</html>
{% endblock %}

app/templates/search.html
{% block body_content %}
<html>

<head>

    <meta charset="utf-8">
    <meta name="author" content="templatemo">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"
          rel="stylesheet">

    <title>Liberty Template - Create NFT Page</title>

    <!-- Bootstrap core CSS -->
    <link href="static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="static/assets/css/fontawesome.css">
    <link rel="stylesheet" href="static/assets/css/templatemo-liberty-market.css">
    <link rel="stylesheet" href="static/assets/css/owl.css">
    <link rel="stylesheet" href="static/assets/css/animate.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
    <!--

    TemplateMo 577 Liberty Market

    https://templatemo.com/tm-577-liberty-market

    -->
</head>
<body>
<div class="item-details-page">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="section-heading">
                    <div class="line-dec"></div>
                    <h2> WORDS <em> SEARCH </em></h2>
                    <h2><br></h2>
                    <h2><br></h2>
                    <h6><br></h6>
                    <h2><br> <br></h2>
                    <h2><br></h2>

                </div>
            </div>
            <div class="col-lg-4">
                <div class="main-button">
                    <a href="{{url_for('home.Index')}}">Anasayfaya Dönmek İçin Tıklayın</a>
                </div>
            </div>
            <div class="col-md-6 offset-md-3">
                <form id="contact" action="" method="post">
                    <div class="row">
                        <div class="col-md-6 offset-md-3">

                            <form action="{{url_for('search.SearchList')}}" method="POST">

                                <fieldset>
                                    <label for="value"><h3>Enter word</h3></label>

                                    <input type="title" name="value" id="value" placeholder="Please enter your word"
                                           autocomplete="on" required formmethod="post">
                                </fieldset>
                            </form>

                        </div>

                        <div class=" col-md-6 offset-md-3">
                            <fieldset>
                                <button type="submit" id="form-submit" class="orange-button" formmethod="post">SEARCH
                                </button>
                            </fieldset>
                        </div>
                    </div>
                </form>
            </div>


        </div>
    </div>
</div>
</body>
</html>
{% endblock %}

app/templates/search_result.html
{% block body_content %}
<html>
<head>

    <meta charset="utf-8">
    <meta name="author" content="templatemo">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"
          rel="stylesheet">

    <title>Liberty Template - Create NFT Page</title>

        <!-- Bootstrap core CSS -->
    <link href="static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">



    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="static/assets/css/fontawesome.css">
    <link rel="stylesheet" href="static/assets/css/templatemo-liberty-market.css">
    <link rel="stylesheet" href="static/assets/css/owl.css">
    <link rel="stylesheet" href="static/assets/css/animate.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
    <!--

    TemplateMo 577 Liberty Market

    https://templatemo.com/tm-577-liberty-market

    -->
</head>

<body>
<div class="discover-items">
    <div class="container">
        <div class="row">
            {% for word in context %}
            <div class="col-lg-4">
                <div class="item">
                    <div class="row">
                        <div class="col-lg-12">

                            <span> <h4> Aranan Kelime :: {{ word_value }}</h4></span>
                        </div>

                        <div class="col-lg-12">
                            <div class="line-dec"></div>
                            <div class="row">
                                <div class="col-12">
                                    <h4> Aranan Kelimenin Anlamı : {{ word }}</h4>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12">
                            <div class="main-button">
                                <a href="{{url_for('home.Index')}}">Anasayfa</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
             {% endfor %}
            <h2><br> <br></h2>
            <h2><br> <br></h2>
            <h2><br> <br></h2>
            <h2><br> <br></h2>
            <h2> </h2>
        </div>
    </div>
</div>

</body>
</html>
{% endblock %}

app/templates/update.html
{% block body_content %}
<html>

<head>

    <meta charset="utf-8">
    <meta name="author" content="templatemo">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"
          rel="stylesheet">

    <title>Liberty Template - Create NFT Page</title>

    <!-- Bootstrap core CSS -->
    <link href="static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="static/assets/css/fontawesome.css">
    <link rel="stylesheet" href="static/assets/css/templatemo-liberty-market.css">
    <link rel="stylesheet" href="static/assets/css/owl.css">
    <link rel="stylesheet" href="static/assets/css/animate.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css"/>
    <!--

    TemplateMo 577 Liberty Market

    https://templatemo.com/tm-577-liberty-market

    -->
</head>
<body>
<div class="item-details-page">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="section-heading">
                    <div class="line-dec"></div>
                    <h2>WORD UPDATE</h2>

                </div>
            </div>
            <div class="col-lg-4">
                <div class="main-button">
                    <a href="{{url_for('home.Index')}}">Anasayfaya Dönmek İçin Tıklayın</a>
                </div>
            </div>

        </div>
    </div>
    <div class="col-md-6 offset-md-3">
        <form id="contact" action="" method="post">
            <div class="row">
                <div class="col-md-6 offset-md-3">
                    <form action="{{url_for('update_word.UpdateWord')}}" method="POST">

                        <fieldset>
                            <label for="word"><h3>Enter Word</h3></label>

                            <input type="title" name="word" id="word" placeholder="Please enter your word"
                                   autocomplete="on" required formmethod="post">
                        </fieldset>
                        <fieldset>
                            <label for="meaning"><h3>Enter Meaning</h3></label>

                            <input type="title" name="meaning" id="meaning" placeholder="Please enter your word"
                                   autocomplete="on" required formmethod="post">
                        </fieldset>
                        <fieldset>
                            <label for="new_value"><h3>Enter New Value</h3></label>

                            <input type="title" name="new_value" id="new_value"
                                   placeholder="Please enter your word"
                                   autocomplete="on" required formmethod="post">
                        </fieldset>

                    </form>

                </div>

                <div class=" col-md-6 offset-md-3">
                    <fieldset>
                        <button type="submit" id="form-submit" class="orange-button" formmethod="post">Update
                        </button>
                    </fieldset>
                </div>
            </div>
        </form>
    </div>


</div>
</div>
</div>
</body>
</html>
{% endblock %}